table CombinedBankingDataset
	lineageTag: 8e3eb337-1744-4f2d-b26e-6b07934b2c26

	column TransactionID
		dataType: int64
		formatString: 0
		lineageTag: 4c8b98b7-9c55-4f64-8ca8-4c72c0125a1c
		summarizeBy: count
		sourceColumn: TransactionID

		annotation SummarizationSetBy = Automatic

	column Transaction_AccountID
		dataType: int64
		formatString: 0
		lineageTag: 9a205f80-261f-4d91-8e7a-2034f21a6590
		summarizeBy: count
		sourceColumn: Transaction_AccountID

		annotation SummarizationSetBy = Automatic

	column TransactionDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: a53c65f4-5b56-4580-8293-83c3d84b2655
		summarizeBy: none
		sourceColumn: TransactionDate

		variation Variation
			isDefault
			relationship: e8e66750-16fa-495a-ac54-f84f677ffb2f
			defaultHierarchy: LocalDateTable_00ca2b2b-4c14-4486-b69a-e91a02ae2c9c.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column TransactionType
		dataType: string
		lineageTag: 5c1eea78-fa58-4a7e-88ac-0aad37897396
		summarizeBy: none
		sourceColumn: TransactionType

		annotation SummarizationSetBy = Automatic

	column Amount
		dataType: double
		lineageTag: df78a559-b985-43f7-be18-31b06ee6d992
		summarizeBy: sum
		sourceColumn: Amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Description
		dataType: string
		lineageTag: 22f0f6dd-1960-4370-a7b0-a05b8bf768aa
		summarizeBy: none
		sourceColumn: Description

		annotation SummarizationSetBy = Automatic

	column Currency
		dataType: string
		lineageTag: 85dea073-733b-485d-b988-d1a681e9af66
		summarizeBy: none
		sourceColumn: Currency

		annotation SummarizationSetBy = Automatic

	column Account_AccountID
		dataType: int64
		formatString: 0
		lineageTag: c1914881-cc11-4942-86df-2976bd042f28
		summarizeBy: count
		sourceColumn: Account_AccountID

		annotation SummarizationSetBy = Automatic

	column Account_CustomerID
		dataType: int64
		formatString: 0
		lineageTag: c55be82e-34b6-4645-9e8a-3afc827c6055
		summarizeBy: count
		sourceColumn: Account_CustomerID

		annotation SummarizationSetBy = Automatic

	column AccountType
		dataType: string
		lineageTag: 1e9461e5-93ef-4b60-bacd-ed8a23025c4e
		summarizeBy: none
		sourceColumn: AccountType

		annotation SummarizationSetBy = Automatic

	column OpenDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 8ffe5001-6c28-47ee-81bf-421374a0a9ad
		summarizeBy: none
		sourceColumn: OpenDate

		variation Variation
			isDefault
			relationship: 517ab0e4-2f50-4012-9a60-9d147af09af9
			defaultHierarchy: LocalDateTable_64962009-2ccb-4d9e-809c-827ca7b60e12.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Balance
		dataType: double
		lineageTag: 5ee3f07b-c7dd-434f-a538-c6d431aaca8d
		summarizeBy: sum
		sourceColumn: Balance

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CustomerID
		dataType: int64
		formatString: 0
		lineageTag: 6f95ceb1-1ad7-420d-a9bc-c3aed57dae7c
		summarizeBy: count
		sourceColumn: CustomerID

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		lineageTag: ee9370ab-ffbf-4fdd-a3d2-6eef8a2722d1
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column DateOfBirth
		dataType: string
		lineageTag: 34dc747f-f1ef-4527-a94a-420201630692
		summarizeBy: none
		sourceColumn: DateOfBirth

		annotation SummarizationSetBy = Automatic

	column Address
		dataType: string
		lineageTag: 877e7cc3-5d8f-48a9-a681-6b82b56ffad6
		summarizeBy: none
		sourceColumn: Address

		annotation SummarizationSetBy = Automatic

	column Email
		dataType: string
		lineageTag: 196c399c-f1a1-4a90-a8e6-c22a61d43a7e
		summarizeBy: none
		sourceColumn: Email

		annotation SummarizationSetBy = Automatic

	column Phone
		dataType: int64
		formatString: 0
		lineageTag: 0a7acc88-8444-41be-9fa5-cf9af9086561
		summarizeBy: sum
		sourceColumn: Phone

		annotation SummarizationSetBy = Automatic

	column Name
		dataType: string
		lineageTag: 1ea77ec4-9f13-4e76-8f06-77848e0ed7b2
		summarizeBy: none
		sourceColumn: Name

		annotation SummarizationSetBy = Automatic

	partition CombinedBankingDataset = m
		mode: import
		source =
				let
				    Source = Sql.Databases("desktop-6gcqen7\SQLEXPRESS"),
				    Power_BI2 = Source{[Name="Power_BI2"]}[Data],
				    dbo_CombinedBankingDataset = Power_BI2{[Schema="dbo",Item="CombinedBankingDataset"]}[Data],
				    #"Replaced Value" = Table.ReplaceValue(dbo_CombinedBankingDataset,null,"unknown",Replacer.ReplaceValue,{"Description"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Replaced Value",{{"Phone", Int64.Type}}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Changed Type","usd","USD",Replacer.ReplaceText,{"Currency"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","savings","Savings",Replacer.ReplaceText,{"AccountType"}),
				    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2","current","Current",Replacer.ReplaceText,{"AccountType"}),
				    #"Replaced Value4" = Table.ReplaceValue(#"Replaced Value3","CURRENT","Current",Replacer.ReplaceText,{"AccountType"}),
				    #"Filtered Rows" = Table.SelectRows(#"Replaced Value4", each true),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Filtered Rows",{{"OpenDate", type date}, {"TransactionDate", type date}}),
				    #"Filtered Rows1" = Table.SelectRows(#"Changed Type1", each true),
				    #"Replaced Value5" = Table.ReplaceValue(#"Filtered Rows1","DEBIT","Debit",Replacer.ReplaceText,{"TransactionType"}),
				    #"Replaced Value6" = Table.ReplaceValue(#"Replaced Value5","payment","Payment",Replacer.ReplaceText,{"Description"}),
				    #"Filtered Rows2" = Table.SelectRows(#"Replaced Value6", each true),
				    #"Added Custom" = Table.AddColumn(#"Filtered Rows2", "Namee", each let
				    n = Number.Mod([TransactionID], 20)
				in
				if n = 0 then "Aarav Sharma"
				else if n = 1 then "Vivaan Patel"
				else if n = 2 then "Aditya Singh"
				else if n = 3 then "Arjun Verma"
				else if n = 4 then "Krishna Joshi"
				else if n = 5 then "Ananya Kulkarni"
				else if n = 6 then "Diya Deshmukh"
				else if n = 7 then "Aisha Khan"
				else if n = 8 then "Priya Nair"
				else if n = 9 then "Sneha Gupta"
				else if n = 10 then "Rahul Mehta"
				else if n = 11 then "Rohan Chavan"
				else if n = 12 then "Karan Yadav"
				else if n = 13 then "Neha Shinde"
				else if n = 14 then "Pooja Pawar"
				else if n = 15 then "Ishaan Malhotra"
				else if n = 16 then "Meera Iyer"
				else if n = 17 then "Kabir Agrawal"
				else if n = 18 then "Saanvi Bhosale"
				else "Reyansh Mishra"),
				    #"Removed Columns" = Table.RemoveColumns(#"Added Custom",{"Name", "Gender"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"Namee", "Name"}}),
				    #"Added Custom1" = Table.AddColumn(#"Renamed Columns", "Gender", each if List.Contains(
				    {
				        "Ananya Kulkarni",
				        "Diya Deshmukh",
				        "Aisha Khan",
				        "Priya Nair",
				        "Sneha Gupta",
				        "Neha Shinde",
				        "Pooja Pawar",
				        "Meera Iyer",
				        "Saanvi Bhosale"
				    },
				    [Name]
				)
				then "Female"
				else "Male"),
				    #"Reordered Columns" = Table.ReorderColumns(#"Added Custom1",{"TransactionID", "Transaction_AccountID", "TransactionDate", "TransactionType", "Amount", "Description", "Currency", "Account_AccountID", "Account_CustomerID", "AccountType", "OpenDate", "Balance", "CustomerID", "Name", "Gender", "DateOfBirth", "Address", "Email", "Phone"})
				in
				    #"Reordered Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

