table 'Measure Table 1'
	lineageTag: e3393e51-d47b-42c6-9a44-77fb0b2a102e

	measure 'Account Count by Type' = ```
			COUNT(CombinedBankingDataset[Account_AccountID])
			
			```
		formatString: 0
		lineageTag: b5da9ccd-ba91-4ed7-9d7f-728f69df5986

	measure 'Customer Count by Gender' = DISTINCTCOUNT(CombinedBankingDataset[CustomerID])
		formatString: 0
		lineageTag: 9d72f29d-712a-4e7d-90e3-89884e3061d6

	measure 'Transaction Type' = COUNT(CombinedBankingDataset[TransactionID])
		formatString: 0
		lineageTag: 5bab4dbe-a3c9-4bc7-84c2-537d15a68928

	measure 'Monthly Transaction Amount' = CALCULATE(SUM(CombinedBankingDataset[Amount]), ALLEXCEPT(CombinedBankingDataset, CombinedBankingDataset[TransactionDate].[Month]))
		lineageTag: 966cafbc-5e20-4533-a11c-3284638f059b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Average Balance' = AVERAGE(CombinedBankingDataset[Balance])
		lineageTag: f1241c49-4b21-4ed6-867d-01a6bc76cf35

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Balance' = SUM(CombinedBankingDataset[Balance])
		lineageTag: 159e0848-ae1b-499e-abc1-31429a87dee2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Inactive Accounts' = CALCULATE(DISTINCTCOUNT(CombinedBankingDataset[Account_AccountID]), FILTER(VALUES(CombinedBankingDataset[Account_AccountID]), CALCULATE(MAX(CombinedBankingDataset[TransactionDate])) < TODAY()-90))
		formatString: 0
		lineageTag: 7d48b402-0395-43ba-9df5-dea826276e88

	measure 'Monthly Transaction Balance' = CALCULATE(SUM(CombinedBankingDataset[Balance]), ALLEXCEPT(CombinedBankingDataset, CombinedBankingDataset[TransactionDate].[Month]))
		lineageTag: 4c7aaebb-9ae8-465b-a081-1f57c1fa3366

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Measure Table 1' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

